// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://issmheckuszfsawozexf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzc21oZWNrdXN6ZnNhd296ZXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDYzMTQsImV4cCI6MjA3NDY4MjMxNH0.WyteU27QaTjFOpkZ3Jp0zox28AgwE9Ypks5IUaLT2Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});